[project]
name = "coin2"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "clickhouse-driver>=0.2.10",
    "confluent-kafka==2.4.0",
    "requests==2.32.3",
    "watchdog>=6.0.0",
    "websockets==12.0",
]
