apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.coin.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    app: coin2
  namespace: coin2
  name: coin2-inserter
spec:
  replicas: 4
  selector:
    matchLabels:
      app: coin2
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.coin.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        app: coin2
    spec:
      containers:
        - name: coin2-insert
          image: vincetran96/coin2:test
          imagePullPolicy: IfNotPresent
          command: ["uv"]
          args: ["run", "-m", "app.etl.insert"]
          envFrom:
          - configMapRef:
              name: env
          resources:
            limits:
              memory: 64Mi
              cpu: 0.25
      restartPolicy: Always
