apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.coin.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    app: coin2
  namespace: coin2
  name: coin2-fetch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coin2
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.coin.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        app: coin2
    spec:
      initContainers:
        - name: coin2-fetch-init
          image: vincetran96/coin2:test
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ["./scripts/py-module.sh", "app.fetch.init"]
          envFrom:
          - configMapRef:
              name: env
      containers:
        - name: coin2-fetch-binance
          image: vincetran96/coin2:test
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ["./scripts/py-module.sh", "app.fetch.binance"]
          envFrom:
          - configMapRef:
              name: env
          resources:
            limits:
              memory: 256Mi
              cpu: 0.5
        - name: coin2-fetch-bitfinex
          image: vincetran96/coin2:test
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ["./scripts/py-module.sh", "app.fetch.bitfinex"]
          envFrom:
          - configMapRef:
              name: env
          resources:
            limits:
              memory: 128Mi
              cpu: 0.5
        - name: coin2-fetch-bybit
          image: vincetran96/coin2:test
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ["./scripts/py-module.sh", "app.fetch.bybit"]
          envFrom:
          - configMapRef:
              name: env
          resources:
            limits:
              memory: 128Mi
              cpu: 0.5
        - name: coin2-fetch-okx
          image: vincetran96/coin2:test
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ["./scripts/py-module.sh", "app.fetch.okx"]
          envFrom:
          - configMapRef:
              name: env
          resources:
            limits:
              memory: 128Mi
              cpu: 0.5
      restartPolicy: Always
