apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.coin.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    app: coin2
  namespace: coin2
  name: coin2-init-hb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coin2
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.coin.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        app: coin2
    spec:
      containers:
        - name: coin2-init-hb
          image: vincetran96/coin2:test
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ["./scripts/init.sh"]
          envFrom:
          - configMapRef:
              name: env
          resources:
            requests:
              memory: 32Mi
              cpu: 0.1
            limits:
              memory: 64Mi
              cpu: 0.5
      restartPolicy: Always
