apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: coin2
  name: coin2-pvc
  labels:
    app: coin2
  annotations:
    volumeType: local
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
    limits:
      storage: 256Mi
